### ISSUE TITLE
Fix or remove following mksh versions

### ISSUE THREAD

**Issue by pawamoy** [shenv/shenv#39]
Versions:

- [ ] R40d
- [ ] R40e
- [ ] R40f
- [ ] R41
- [ ] R41b
- [ ] R41c
- [ ] R42
- [ ] R42b
- [ ] R43
- [ ] R44

```
] conftest.c:29:5: error: variably modified 'ari_sign_32_bit_and_wrap' at file scope
]  cta(ari_sign_32_bit_and_wrap,
]      ^
] conftest.c:7:35: note: in definition of macro 'cta'
]  #define cta(name, assertion) char name[(assertion) ? 1 : -1]
]                                    ^
==> whether compile-time assertions pass... no
```

**Comment by pawamoy** [comment]
@mirabilos, any hint/idea on how to fix these builds :smile: ?

**Comment by mirabilos** [comment]
Build these versions with a compiler that does not suffer from [GCC bug 55009](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55009). That would be GCC 4.7 or older, or a non-GCC compiler.

Alternatively, for R41 and up, read [this](http://www.mirbsd.org/mksh_old.htm#p41), particularily the part about the GCC bug, the CPPFLAGS-based workaround **and that you absolutely _must_ run the testsuite and check that it passes** when used. (You’ll likely also need `-fwrapv` with that.)

Later versions of mksh have a completely rewritten arithmetic expression evaluation code which emulates `signed` integer operations using an `unsigned` integer type, so that is no longer a problem.

I _strongly_ suggest using a non-affected compiler over the workaround above.

**Comment by pawamoy** [comment]
Alright, thank you very much for the tips 😃!

**Comment by pawamoy** [comment]
So, I built mksh-R41 with `CPPFLAGS='-DMKSH_GCC55009 -fwrapv' ./Build.sh` and it worked. `arith-mandatory` test is passing, but I have two unexpected failures: `regression-63` and `pipeline-3`. Does it mean I shouldn't use the compiled executable?

**Comment by pawamoy** [comment]
I guess I will try to update the definitions so they make use of a non-affected compiler.

**Comment by mirabilos** [comment]
Timothée Mazzucotelli dixit:

>So, I built mksh-R41 with `CPPFLAGS='-DMKSH_GCC55009 -fwrapv'
>./Build.sh` and it worked. `arith-mandatory` test is passing, but I
>have two unexpected failures: `regression-63` and `pipeline-3`. Does

Did you get these before?

Can you share the build log?

>it mean I shouldn't use the compiled executable?

Looks like these are pretty bad errors, so yes.

**Comment by pawamoy** [comment]
Sure, here is the build log for mksh-R41: https://pastebin.com/8d0CwZv4. I never tried to run the test suite before, I will see if it happens for other versions and tell you here.

**Comment by pawamoy** [comment]
And the tests results for each version (except 40d,e,f since I wasn't able to build those 3): https://pastebin.com/Rtinmn4n. They are actually passing now 😕 Maybe because I'm on another machine. Will investigate.

**Comment by mirabilos** [comment]
Hm, no warnings in the build log. I had hoped that something would have shown up.

Perhaps using an older compiler for the older releases is really the way to go. I modernised tons of code since then.

**Comment by pawamoy** [comment]
Hi @mirabilos, I'm eventually removing these definitions from the project. I'm totally okay with reopening this issue if someone wants to fix it though. I'm just cleaning up my big pile of issues :wink:

I want to thank you again for the help you provided me. So thank you :heart:!
